from typing import Any, Dict, List, Optional

from logging_utils import get_logger
from models import Finding, RiskSummary, URLScanResult

logger = get_logger(__name__)


def build_text_report(
    *,
    metadata: Dict[str, Any],
    url_result: Optional[URLScanResult],
    summary: RiskSummary,
    findings: List[Finding],
) -> str:
    """Build a developer-friendly, text-only report."""
    logger.info("Building text report with %d findings", len(findings))

    lines: List[str] = []

    app_name = (metadata.get("app") or {}).get("name", "Unknown Application")
    lines.append("============================================================")
    lines.append("       ATTACK SIMULATION ENGINE (ASE) – SECURITY REPORT")
    lines.append("============================================================")
    lines.append(f"Application: {app_name}")
    lines.append("Generated by: ASE (Internal Developer Tool)")
    lines.append("Note: All checks are heuristic and non-intrusive.")
    lines.append("Use only on systems you own or are authorized to test.")
    lines.append("")
    
    lines.append("------------------------------------------------------------")
    lines.append("1. EXECUTIVE SUMMARY")
    lines.append("------------------------------------------------------------")
    lines.append(
        f"Overall Risk Score: {summary.overall_score:.1f} / 10 "
        f"[{summary.overall_severity.upper()}]"
    )
    lines.append("")
    lines.append("Category Risk Overview:")
    for cs in summary.category_scores:
        lines.append(
            f"  * {cs.category:<30} : {cs.score:.1f} / 10 ({cs.severity})"
        )
    lines.append("")

    lines.append("------------------------------------------------------------")
    lines.append("2. APPLICATION OVERVIEW")
    lines.append("------------------------------------------------------------")
    app = metadata.get("app", {})
    env = app.get("environment", "N/A")
    stack = app.get("stack", {})
    backend = stack.get("backend", "N/A")
    frontend = stack.get("frontend", "N/A")
    framework = stack.get("framework", "N/A")
    lines.append(f"Environment : {env}")
    lines.append(f"Backend     : {backend}")
    lines.append(f"Frontend    : {frontend}")
    lines.append(f"Framework   : {framework}")
    lines.append("")

    if url_result is not None:
        lines.append(f"Target URL            : {url_result.original_url}")
        lines.append(f"Final URL             : {url_result.final_url}")
        lines.append(f"Status Code           : {url_result.status_code}")
        lines.append(f"HTTPS Enabled         : {'Yes' if url_result.https else 'No'}")
        lines.append(f"Approx. Response Time : {url_result.elapsed_ms:.0f} ms")
        lines.append("")

    lines.append("------------------------------------------------------------")
    lines.append("3. DETAILED FINDINGS")
    lines.append("------------------------------------------------------------")
    if not findings:
        lines.append("No findings were generated.")
    else:
        for idx, f in enumerate(findings, start=1):
            lines.append(f"Finding #{idx}: {f.title}")
            lines.append(f"Severity: {f.severity.upper()} | ID: {f.id}")
            lines.append(f"Category: {f.category}")
            lines.append(f"Source  : {f.source}")
            lines.append(
                f"Risk    : {f.likelihood} (Likelihood) x {f.impact} (Impact) = {f.raw_score}"
            )
            lines.append(f"Description:\n  {f.description}")
            lines.append(f"Recommendation:\n  {f.recommendation}")
            lines.append("-" * 60)
            lines.append("")

    lines.append("------------------------------------------------------------")
    lines.append("4. SIMULATED ATTACK SCENARIOS (HEURISTIC)")
    lines.append("------------------------------------------------------------")
    lines.append(
        "The following scenarios are **simulated** based on metadata and headers only. "
        "No real exploitation was performed."
    )
    lines.append("")
    sim_findings = [f for f in findings if f.source == "simulation"]
    if not sim_findings:
        lines.append("No simulation-specific findings were generated.")
    else:
        for f in sim_findings:
             lines.append(f"- {f.title} ({f.category}, {f.severity})")
    lines.append("")

    lines.append("------------------------------------------------------------")
    lines.append("5. RECOMMENDED NEXT STEPS")
    lines.append("------------------------------------------------------------")
    lines.append(
        "1) Address High and Medium severity findings starting with Authentication, "
        "Data Protection, and API Security."
    )
    lines.append(
        "2) Introduce automated security testing (SAST/DAST) and security linters "
        "in your CI/CD pipeline."
    )
    lines.append(
        "3) Periodically review logs and implement centralized monitoring for "
        "suspicious activity."
    )
    lines.append(
        "4) Consider a dedicated, authorized penetration test for critical systems, "
        "complementing this heuristic tool."
    )
    lines.append("")
    lines.append("============================================================")
    lines.append("                   END OF REPORT")
    lines.append("============================================================")

    return "\n".join(lines)
